version: "3"
services:
  redis:
    image: redis:alpine
    command: redis-server --port 6379
    container_name: redis_devee
    hostname: redis_devee
    labels:
      - "name=redis"
      - "mode=standalone"
    ports:
      - "6379:6379"